# SPDX-License-Identifier: Apache-2.0
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=49152
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_EVENTS=y
CONFIG_DYNAMIC_INTERRUPTS=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Coprocessor feature selection.
CONFIG_WLH_WIFI_BACKEND=y
CONFIG_WLH_USB_TRANSPORT=y
