/* SPDX-License-Identifier: Apache-2.0 */
#ifndef WLH_FIRMWARE_CONFIG_H
#define WLH_FIRMWARE_CONFIG_H

#define WLH_MCU_NAME "BL616"
#define WLH_BOARD_PROFILE "bl616-spi-usb/ai_m62_12f_kit"
#define WLH_IMPLEMENTATION_VERSION "0.1.0"

#define WLH_USB_VID 0x303au
#define WLH_USB_PID 0x8201u
#define WLH_USB_MAX_POWER_MA 500u
#define WLH_USB_BUS_ID 0u
#define WLH_USB_IRQ 37u
#define WLH_USB_EP_OUT 0x01u
#define WLH_USB_EP_IN 0x81u
#define WLH_USB_EP_MPS 512u
#define WLH_USB_RX_RING_SIZE (2u * 4096u + WLH_USB_EP_MPS)
#define WLH_USB_CONTROL_TX_QUEUE_DEPTH 4u
#define WLH_USB_DATA_TX_QUEUE_DEPTH 28u
#define WLH_USB_TX_TIMEOUT_MS 2000u

#define WLH_WIFI_TX_QUEUE_DEPTH 16u
#define WLH_WIFI_MAX_ETHERNET_FRAME_SIZE 1518u
#define WLH_WIFI_SCAN_MAX_RESULTS 24u

#define WLH_CORE_QUEUE_DEPTH 64u
#define WLH_CORE_TASK_STACK 8192u
#define WLH_CORE_TASK_OSAL_PRIORITY 7
#define WLH_INITIAL_CREDIT WLH_WIFI_TX_QUEUE_DEPTH
#define WLH_STOP_TIMEOUT_MS 3000u

#endif
